services:
  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./api/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

volumes:
  postgres_data:
